---
# tasks file for logstash-role
  - name: Create group for Logstash
    group:
      name: logstash
      state: present
    tags: logstash
  - name: Add user for Logstash
    user:
      name: logstash
      group: logstash
      shell: /bin/bash
    tags: logstash
  - name: Upload tar.gz Logstash from remote URL
    get_url:
      url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
      dest: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"  #если указать просто директорию без имени файла, то имя файла будет взято из source
      mode: 0755
      timeout: 60  #увеличиваем, так как 10 сек (по умолчанию) не хватает для скачки и будет ошибка
      force: true
      owner: root
      group: root
    register: get_logstash
    until: get_logstash is succeeded # пробуем, пока не скачается успешно (по умолчанию 3 раза)
    tags: logstash
  - name: Create directrory for Logstash
    file:
      state: directory
      path: "{{ logstash_home }}"
      owner: logstash
      group: logstash
      mode: 0755
    tags: logstash
  - name: logstash Elasticsearch in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
      dest: "{{ logstash_home }}"
      extra_opts: [--strip-components=1]  #удаляем 1 род. директорию при извлечении
      owner: logstash
      group: logstash
      mode: 0755
      creates: "{{ logstash_home }}/bin/logstash"  #если этот файл существует, то мы этот Task пропускаем
    tags:
      - skip_ansible_lint
      - logstash
  - name: Set environment Logstash
    become: yes
    template:
      src: templates/logstash.sh.j2
      dest: /etc/profile.d/logstash.sh
      owner: root
      group: root
      mode: 0644
    tags: logstash
  - name: Create Logstash config
    become: yes
    template:
      src: templates/logstash.yml.j2
      dest: "{{ logstash_home }}/config/logstash.yml"
      backup: true #каждый раз, когда конфиг будет меняться, он будет делать бэкап предыдущей версии в тойже директории.
      owner: logstash #who owner of files
      group: logstash
      mode: 0755